### ISSUE TITLE
fastly

### ISSUE THREAD

**Issue by powerloadersu** [Isoaxe/cors-server#13]
How do I make it work on fastly.com?

**Comment by isoaxe** [comment]
I don't think it's possible to deploy to a CDN like Fastly. Is there a particular reason you want to deploy there?

I would strongly suggest you opt for Fly or Firebase.

**Comment by powerloadersu** [comment]
I just wanted to know if it was possible.

**Comment by isoaxe** [comment]
It's not, afaik.
