### ISSUE TITLE
Different behavior between cors-everywhere webpage and Firebase cors-server

### ISSUE THREAD

**Issue by EKOzkan** [Isoaxe/cors-server#16]
Firstly, thank you for this repo, it is such a lifesaver for CORS related problems. But there is an issue that I faced when using the Firebase version. When I use the https://cors-anywhere.herokuapp.com/ as a proxy, I can scrape the YouTube urls without any problem, but when I try to use my server It gives me video is not available response. Do you have any idea what causes this issue? Other urls works fine btw.

**Comment by isoaxe** [comment]
Glad you found the repo useful! Not sure what the issue might be there I'm afraid, but I do know others were also finding the Firebase proxy problematic.

Have you tried using the Fly.io proxy instead and if so do the same issues occur there too? You can try it locally using the `https://cors-server.fly.dev/` proxy before you set up your own one to see if it works.

**Comment by EKOzkan** [comment]
That fixed the problem, thanks 👍
