### ISSUE TITLE
Getting cors error even after following all the steps you have mentioned on readme

### ISSUE THREAD

**Issue by devalvora20** [Isoaxe/cors-server#18]
Hello,
I followed all the steps for firebase on your readme, but Im still getting a cors error.
"Access to fetch at 'xyz' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."
Can you please help me with this?

**Comment by isoaxe** [comment]
Some people were having issues with Firebase, usually with `POST` requests.

The easiest way forward is probably to use `fly.io` instead. Give that a go and let me know how you get on.

**Comment by devalvora20** [comment]
Oh actually I realized that the issue is that I did not add "allUsers" as permission to call my firebase function. After I added that, It worked fine atlease from my localhost:3000 port, however Im still facing issues when I actually try to call it from the website that I have hosted on netlify. 
Nevertheless, thanks for this repo, it is really helpful but you might want to add that additional section for the firebase readme to enable the permissions

**Comment by isoaxe** [comment]
Yeah no problem. Is that `allUsers` permission that you have set from the Google Cloud Platform dashboard or where are you referring to?

Also did you attempt to deploy from fly.io or not? If the latter, I would really recommend giving it a go as it should only take a few minutes and could solve your issues.
