### ISSUE TITLE
Always receiving status 503 error when performing HTTP POST to Firebase Function

### ISSUE THREAD

**Issue by restoredtemecula** [Isoaxe/cors-server#6]
Each time I attempt to send a HTTP POST request to my Firebase Function, I receive an error in my browser console, a status 503 error. 

I am attempting the post request from a squarespace website in chrome browser. I am sending the exact same information that was sent when using Heroku as 'middleware' for the POST requests from this page. It is a very basic JSON string. Example below.

`{
                "to": ["ExponentPushToken[dhLJeWNqW61r1ZBUkAwOtA]"],
                "title": "Hello World! ",
                "body": "I am Mark Logue, and I made this app!",
                "sound": "default",
                "data": {"event": ""}
  }`

The website I am sending the post request from is on my cors-anywhere whitelist with the index.js file. 

There are two concerning logs that I found within the Firebase Function (Google Cloud) logs for this function. First when I look at the log for the POST request, it shows in initial Options status of 204, see the log below:

`{
  "insertId": "6372a16400076996e307afbc",
  "httpRequest": {
    "requestMethod": "OPTIONS",
    "requestUrl": "https://proxy-hwp6dcya3a-uc.a.run.app/https://exp.host/--/api/v2/push/send",
    "requestSize": "761",
    "status": 204,
    "responseSize": "863",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "remoteIp": "47.149.74.45",
    "referer": "https://restoredtemecula.church/",
    "serverIp": "216.239.36.53",
    "latency": "1.341490290s",
    "protocol": "HTTP/1.1"
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "configuration_name": "proxy",
      "location": "us-central1",
      "revision_name": "proxy-hvnfg",
      "service_name": "proxy",
      "project_id": "restored-temecula-mobile-app"
    }
  },
  "timestamp": "2022-11-14T20:13:24.485782Z",
  "severity": "INFO",
  "labels": {
    "instanceId": "0074e2ccb212737e5aad036cd3cebcfe4d5f35f47d168e939180e59572278e50b0cb6b75be2da34e4a6c16bbab33905987e3d9640d703e97d54f9708a58c14dc9f29",
    "goog-managed-by": "cloudfunctions"
  },
  "logName": "projects/restored-temecula-mobile-app/logs/run.googleapis.com%2Frequests",
  "trace": "projects/restored-temecula-mobile-app/traces/ca1ce4c9d9432e0ab47d756bff0cf16c",
  "receiveTimestamp": "2022-11-14T20:13:24.492659539Z",
  "spanId": "14113124528369450882",
  "traceSampled": true
}`

Second, I receive in the 503 status error both in the logs in firebase function (google cloud) and in my chrome browser (logging the server response for the POST request). Here is the firebase funciton/google cloud log for the 503 status:

`{
  "insertId": "6372a177000a1e8dbb2702ed",
  "httpRequest": {
    "requestMethod": "POST",
    "requestUrl": "https://proxy-hwp6dcya3a-uc.a.run.app/https://exp.host/--/api/v2/push/send",
    "requestSize": "1171",
    "status": 503,
    "responseSize": "1201",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "remoteIp": "47.149.74.45",
    "referer": "https://restoredtemecula.church/",
    "serverIp": "216.239.36.53",
    "latency": "19.114303071s",
    "protocol": "HTTP/1.1"
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "location": "us-central1",
      "configuration_name": "proxy",
      "service_name": "proxy",
      "revision_name": "proxy-hvnfg",
      "project_id": "restored-temecula-mobile-app"
    }
  },
  "timestamp": "2022-11-14T20:13:43.663181Z",
  "severity": "ERROR",
  "labels": {
    "instanceId": "0074e2ccb212737e5aad036cd3cebcfe4d5f35f47d168e939180e59572278e50b0cb6b75be2da34e4a6c16bbab33905987e3d9640d703e97d54f9708a58c14dc9f29",
    "goog-managed-by": "cloudfunctions"
  },
  "logName": "projects/restored-temecula-mobile-app/logs/run.googleapis.com%2Frequests",
  "trace": "projects/restored-temecula-mobile-app/traces/9dacc5993e58e51bcd37c3c3b8b461e6",
  "receiveTimestamp": "2022-11-14T20:13:43.670755140Z",
  "spanId": "17443868335897408337"
}`

<img width="1185" alt="Untitled 5" src="https://user-images.githubusercontent.com/83615439/201766216-6d21e065-bcc9-4de1-a4e4-617a08d98905.png">

Lastly, when I attempt to perform the POST request in terminal using CURL, I receive the same response as if I were simply navigate to the link (https://proxy-hwp6dcya3a-uc.a.run.app/https://exp.host/--/api/v2/push/send) in my browser. E.g below shows the CURL command follow by the response, directly copied from terminal and pasted here.

`curl -H "Content-Type: application/json" -X POST "https://proxy-hwp6dcya3a-uc.a.run.app/https://exp.host/--/api/v2/push/send" -d '{
  "to": "ExponentPushToken[dhLJeWNqW61r1ZBUkAwOtA]",
  "title":"hello",
  "body": "world"
}'
Missing required request header. Must specify one of: origin,x-requested-with% `

"Missing required request header. Must specify one of: origin,x-requested-with"... Would love any assistance on this! Thanks in advance!

**Comment by isoaxe** [comment]
With regards to the `Missing required request header. Must specify one of: origin,x-requested-with` message when navigating to `https://proxy-hwp6dcya3a-uc.a.run.app/https://exp.host/--/api/v2/push/send` from the browser - that is to be expected. It is what we specified within the `requireHeader` field in `index.js`. Have a look at the CORS Anywhere [documentation](https://github.com/Rob--W/cors-anywhere#server) on the subject. The requirement for these headers is to prevent users from using the proxy for normal browsing (i.e. only intended for HTTP requests). However, cURL commands don't attach those headers either.

As a demonstration, run `curl -H "Content-Type: application/json" -X POST "postman-echo.com/post"` - you will get the expected response. Then try prepending with your proxy, i.e. `curl -H "Content-Type: application/json" -X POST "https://proxy-hwp6dcya3a-uc.a.run.app/postman-echo.com/post"` and you will get the `Missing required request header` message as with your request. Finally, add the header i.e. `curl -H "origin: http://localhost:3000" -H "Content-Type: application/json" -X POST "https://proxy-hwp6dcya3a-uc.a.run.app/postman-echo.com/post"` to the proxied request and it will work.

I successfully ran the POST request _without_ the proxy via cURL and separately using Postman, getting the following response:
`{"data":{"status":"ok","id":"83d56fba-b332-419f-902c-5cb62d48feef"}}`. Using the proxy and attaching an `origin` header per the demo above results in `upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection termination`

Hopefully the above might be of some use, though it doesn't resolve the issue. I'll have another look later when I have time.

**Comment by isoaxe** [comment]
Also, have you tested with a local instance of `cors-server` and locally hosting the website making the API request? If so do you experience the same issue as when hosting both remotely?

**Comment by isoaxe** [comment]
I had another little look at it. So when I use [your](https://proxy-hwp6dcya3a-uc.a.run.app/) proxy server in the [ravenous](https://github.com/Isoaxe/ravenous/blob/master/src/util/searchYelp.js#L5) app (my use case), it works fine. You can fork that repo and give it a go if you like.

Also, don't worry about the `204` response - that is normal and will be present with a successful request too (i.e. you will get a `204` and a `200` when successful).

The problem likely lies with the API endpoint that you are trying to reach. The server might have a problem with the use of a proxy (hence the `503 Service Unavailable` error).

**Comment by isoaxe** [comment]
In case anyone else looks at this, I recreated the errors by replacing the contents of [`searchYelp`](https://github.com/Isoaxe/ravenous/blob/master/src/util/searchYelp.js) with the code below:

```
async function searchYelp(term, location, priceString, sortBy) {
  const corsProxy = "https://proxy-ibmasyzzya-uc.a.run.app/";
  const restoredTemeculaApi = "https://exp.host/--/api/v2/push/send";
  const data = { "to": "ExponentPushToken[dhLJeWNqW61r1ZBUkAwOtA]", "title":"hello", "body": "world" };
  const fetchOptions = {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(data)
  };

  const response = await fetch(corsProxy + restoredTemeculaApi, fetchOptions);
  console.log(response);
  return response;
}

export default searchYelp;
```

The [`BusinessList`](https://github.com/Isoaxe/ravenous/blob/master/src/components/App/App.js#L29-L32) component in `App.js` also needs to be removed in order for the app to build.

Responses for [`204 No Content`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) and [`503 Service Unavailable`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) will be displayed in the GCF logs associated with the proxy server, accessable from the Firebase console in the browser as pointed out by @restoredtemecula. The `503` is also in the browser console after the request fails.

**Comment by restoredtemecula** [comment]
Thanks for looking into this with me. The oddity here is that it was working totally fine in the Heroku environment. I also spent a couple minutes, as a contingency, migrating the few Heroku apps I built over to railway and cors-anywhere works fine in that environment too. The draw to firebase was that, for the same project, I use firestore and realtime db, so I thought it'd be nice to house it all in one place. It might be a bit over my head at this point to figure out how to make cors-anywhere work on firebase at this point. Not as simple a migration as I had hoped, and I am a noob.

**Comment by isoaxe** [comment]
Sure, not a problem. So just to clarify, had you previously hosted your `cors-server` on Heroku where it was working fine and migrating to Firebase resulted in the `503` error for some API requests passing through it? Or was it moving the apps themselves from Heroku to Firebase that caused the issue? Also, do you control the server that hosts the `https://exp.host/--/api/v2/push/send` endpoint and if so how is that hosted and did it change?

I would advise opening an issue on the actual `cors-anywhere` repo and try to be very specific on what arrangement worked and what didn't. The author of that repo knows much more than me about it, though he's busy so might not get time.

Failing that, I would suggest using Heroku if that worked for you before. They have [revised their pricing](https://blog.heroku.com/new-low-cost-plans) so you can get a dyno for 1¢ per hour uptime.

**Comment by restoredtemecula** [comment]
So to clarify, it was the former scenario you mentioned above, I had "previously hosted your cors-server on Heroku where it was working fine and migrating to Firebase resulted in the 503 error for some API requests passing through it?" And to further clarify, everything works currently without changing a single line of code (on my end) after migrating to railway, which  for the scale of my usage will likely keep me in a free tier for the foreseeable future. 

I changed nothing in attempting to work with firebase functions apart from what you listed in your instructions. I will still spend some time looking into it and seeing if I can get the issue with cors-server on firebase worked out, but the railway tech seems to be VERY user friendly and functional for me for the time being, so getting it up on firebase is less urgent at this point. 

Thanks again for all the help and the suggestions. I think Railway is a huge win, at least for the projects that I had on Heroku. A very seamless transition, and a great looking UI.

**Comment by isoaxe** [comment]
Yeah Railway have a nice platform alright. Hopefully they don't cut you off like they did with me near the end of the month.

Also if you do figure out a solution, please post it here to help others experiencing the same issue.

**Comment by isoaxe** [comment]
Hi @restoredtemecula. Maybe you have seen [this](https://github.com/Rob--W/cors-anywhere/issues/434#issuecomment-1324671425) already, but [fly.io](https://fly.io/launch/heroku) might be your best bet if and when you run out of Railway hours.

I'll close out the issue as that should resolve your problem. The `503` was specific to Firebase and the server / API endpoint you were attempting to reach. Feel free to reopen the issue if the need arises.

**Comment by PeWu** [comment]
Possibly related: https://github.com/Rob--W/cors-anywhere/issues/445

**Comment by isoaxe** [comment]
Yes that's interesting. Works when sending a POST request to Postman using either the proxy or with a data payload, but not both.

Maybe there is an issue sending data with the Firebase implementation of `cors-server`. My use case only involves a GET request to the Yelp API, would be good to know if anyone has successfully sent data via a POST request using it...
